name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          token: ${{ secrets.NPM_TOKEN }}
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: echo ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm publish --provenance --access public
