name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: "servtec/axios:${{ steps.version.outputs.version }}"
          context: .
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          token: ${{ secrets.NPM_TOKEN }}
          node-version: '20.x'
          scope: serv-tec
          registry-url: 'https://registry.npmjs.org'
      - run: echo ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm publish --provenance --access public
